import Navigation from "@/components/navigation/navigation";
import { rubik, sourGummy } from "./fonts";
import "./globals.css";
import Footer from "@/components/footer/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${sourGummy.variable}`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
